### ISSUE TITLE
memcache Get has unintuitive API

### ISSUE THREAD

**Issue by vadimsht** [luci/gae#3]
What one expects:
memcache.Get("key") -> (Item, error).

What one has to do:
item := memcache.NewItem("key")
memcache.Get(item) -> error

Also it would be nice to document ErrCacheMiss in Get() comment, I had to guess it (having never been exposed to GAE Golang APIs before).

**Comment by riannucci** [comment]
Ok, so... the reason I did this is basically so that when you're dealing with a big collection of items, you can create a bunch of items at the beginning and then add/set/get whatever them without having to convert back and forth to []string.

Example of what I'm talking about: https://github.com/luci/gae/blob/master/filter/dscache/ds.go#L47

If I just changed Get and not GetMulti, do you think that would be OK?

**Comment by riannucci** [comment]
Yeah, actually, I think this makes sense, even though it's a bit quirky. I have a CL and it looks pretty good.

**Comment by riannucci** [comment]
CL is here: https://codereview.chromium.org/1354333002

**Comment by riannucci** [comment]
Fixed
