### ISSUE TITLE
dscache not setting Item.Value in transactions

### ISSUE THREAD

**Issue by SlothNinja** [luci/gae#31]
I can’t seem to get transactions to work with the dscache filter.  I keep receiving the error:

ERROR: dscache: HARD FAILURE: dsTxnState.apply(): mc.SetMulti :: {"error":"proto: required field \"Item.Value\" not set"}
2015/12/22 05:19:54 ERROR: proto: required field "Item.Value" not set

If I remove the dscache filter, they appear to work.

**Comment by riannucci** [comment]
Here's a CL to fix: https://chromiumcodereview.appspot.com/1541183002

The issue is that the current in-memory implementation of memcache is perfectly happy to accept an Item with a nil Value, because that's a pretty sane thing to do :). The prod implementation doesn't share that and prefers to trap the user with an error :D. I guess it's possible that you forgot to put a Value on an Item, but I think that's probably a GIGO thing at that point.

**Comment by riannucci** [comment]
(And thank you @SlothNinja for the bug report! :+1: )

**Comment by riannucci** [comment]
@SlothNinja, I'm going to wait to commit that change until I get code review from one of my teammates. If you want to, you should be able to apply the patch locally (you can get the raw patch [here](https://chromiumcodereview.appspot.com/download/issue1541183002_1.diff)) in the meantime.

**Comment by riannucci** [comment]
Fixed
