### ISSUE TITLE
search API support

### ISSUE THREAD

**Issue by bsr203** [luci/gae#65]
Hi,

Is it possible to add support for search API?

I tried to use `aetest.NewContext()` for search, but met with following difficulty.
It works if I just insert to search index, but in normal usage, I persist the entities (datastore + search index) same time. My datastore code persist the entities through `	"github.com/luci/gae/service/datastore"`, and when use aetest context, I get following exception.

```
--- FAIL: TestInsert (2.89s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12860d]

goroutine 7 [running]:
panic(0x492da0, 0xc4200121d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008eb40)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x492da0, 0xc4200121d0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/luci/gae/service/datastore.GetKeyContext(0x76fe40, 0xc4201c8b70, 0x0, 0xc42004fc58, 0x2, 0x2)
	/Users/bsr/go/src/github.com/luci/gae/service/datastore/context.go:93 +0x4d
github.com/luci/gae/service/datastore.NewKey(0x76fe40, 0xc4201c8b70, 0xc42018ec04, 0x7, 0xc420190a40, 0x18, 0x0, 0x0, 0x76fe40)
	/Users/bsr/go/src/github.com/luci/gae/service/datastore/interface.go:201 +0x4d

```

this is the code where it throws

```
// GetKeyContext returns the KeyContext whose AppID and Namespace match those
// installed in the supplied Context.
func GetKeyContext(c context.Context) KeyContext {
	ri := info.Raw(c)
	return MkKeyContext(ri.FullyQualifiedAppID(), ri.GetNamespace())  // <--- line 93
}

```

**Comment by danjacques** [comment]
Yeah unfortunately the `Context`s are not interchangeable; an AppEngine SDK `Context` is independent from a `luci/gae` `Context` by design, since the two handle data differently.

Although it's definitely something that would be good to add, search API support isn't currently a high priority for us. In the meantime, you could maintain two `Context`s, one for AppEngine SDK operations and one for `luci/gae`.

Another option would be to augment `impl/memory` with a `With...` style method to install `luci/gae` services into a supplied `Context` (instead of generating a new one). This would let you install `luci/gae` into the existing `aetest` `Context`. Think that would do it?

**Comment by bsr203** [comment]
I think selectively installing service would be the best solution. Even using two different context won't help as typically one build the search index while making any modification to datastore, so I may have to think about clever way to separate them to make the test work. 

I could leave out this test if it is too much work for you and I am ok with it as everything else works great. But, if you think selectively setting services would benefit more use cases, it would be great to have. 

Thank you for very quick response. you guys rock :-)

**Comment by danjacques** [comment]
So you should be able to use `impl/memory`'s [Use](https://godoc.org/github.com/luci/gae/impl/memory#Use) method on the `Context` returned by `aetest`'s [NewContext](https://godoc.org/google.golang.org/appengine/aetest#NewContext) method. This will install `luci/gae` services into the `aetest` `Context`.

The resulting `Context` will install `luci/gae` datastore etc. into the `Context`, allowing you to use `service/*` packages. It will also be backed by `aetest`, so the AppEngine search API should work with it. This should be compatible because the search API and datastore don't share any state (AFAIK).

```go
import (
  "testing"

  "google.golang.org/appengine/aetest"

  "github.com/luci/gae/impl/memory"
)

func TestMyThing(t *Testing.T) {
  c, closeAETest, err := aetest.NewContext()
  if err != nil { ... }
  defer closeAETest()

  // Add luci/gae memory services.
  c = memory.Use(c)

  // You should be able to use "c" for search API and "service/datastore" calls.
  // ...
}
```

These tests would run slower because you have to spin up an `aetest` server instance each time, so I'd make a point of isolating the search API parts of your code from your pure `luci/gae` parts so you can run as many pure `luci/gae` tests quickly as possible.

**Comment by riannucci** [comment]
(To answer the original question in the bug: Yes, it would be amazing to add a fake in-memory search API to compliment the datastore one :). It's not entirely clear to me how to do this, however. If anyone has implementation ideas, they're definitely welcome!)

**Comment by bsr203** [comment]
@danjacques your solution worked great. thank you very much.
@riannucci afaik, https://github.com/blevesearch/bleve is the best search solution for fulltext search in go. At the same time, I don't know how compatible it is with GAE API and some of the features may not be available. I am ok with the slowness of few test and glad the above mentioned sol works. 

thanks again for all your support.
