### ISSUE TITLE
Help with GetPLS

### ISSUE THREAD

**Issue by bsr203** [luci/gae#68]
Hi,

I am trying to write an interface like `func GetMulti(ctx context.Context, ids []string, dst interface{}) error`, to get all the entities on a list of keys.

Similar to [GetAll](https://github.com/luci/gae/blob/master/service/datastore/interface.go#L415), I am trying to load the `dst` with the result. 

```
errs := map[int]error{}
i := 0
err := filterStop(datastore.Raw(ctx).GetMulti(keys, nil, func(pm datastore.PropertyMap, err error) error {
	slice.Set(reflect.Append(slice, reflect.New(slice.Type().Elem()).Elem()))
	itm := slice.Index(i)
	// mat.setKey(itm, k)
	// err := mat.setPM(itm, pm)
	datastore.GetPLS(itm).Load(pm)
	i++
	return nil
}))
```

which gives error
```
panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 4 [running]:
panic(0x447620, 0xc42022ff60)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42020a300)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x447620, 0xc42022ff60)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.Value.IsNil(0x4d2d40, 0xc42022ff40, 0x99, 0xc42022ff40)
	/usr/local/go/src/reflect/value.go:977 +0xf9
github.com/luci/gae/service/datastore.GetPLS(0x4d2d40, 0xc42022ff40, 0xc42022ff40, 0x4d2d40)
	/Users/bsr/Work/external_dev/src/github.com/luci/gae/service/datastore/pls.go:222 +0x87
```

Seems like I am passing wrong type to `GetPLS`, and tried `itm.Addr()`, with the same result. Any help is greatly appreciated.

thanks.
bsr.

**Comment by danjacques** [comment]
From `GetPLS` [documentation](https://github.com/luci/gae/blob/a9451708f36e28488bea90aab94ce84153ead26f/service/datastore/pls.go#L12):
```go
// obj must be a non-nil pointer to a struct of some sort.
```

I'm not sure what type your slice is, but, at least in the `panic` that you provided, you're passing a struct value rather than a pointer to a struct value.

On a larger scale, though, reflection and instantiation are full of nuances and complexities (see [multiarg](https://github.com/luci/gae/blob/a9451708f36e28488bea90aab94ce84153ead26f/service/datastore/multiarg.go) for examples). It looks like you're trying to automatically populate a slice with results of a `Get` given a set of keys. Is there any reason you can't avoid this entire problem and just do something like:

```go
s := make([]MyType, len(keys))
for i, k := range keys {
  if  !datastore.PopulateKey(&s[i], k) {
    // error
  }
}
err := datastore.Get(ctx, s)
```

**Comment by bsr203** [comment]
thanks @danjacques I was migrating to luci/gae and wasn't aware all the options available. Will follow your example. thanks again.
